%YAML:1.0

#---------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#---------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Left Camera calibration and distortion parameters (OpenCV)
Camera.fx: 615.6707153320312
Camera.fy: 615.962158203125
Camera.cx: 328.0010681152344
Camera.cy: 241.31031799316406
# Camera.fx: 639.666809
# Camera.fy: 639.387268
# Camera.cx: 641.144348
# Camera.cy: 402.583496

# distortion parameters
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
# Camera.k1: -0.056473
# Camera.k2: 0.065678
# Camera.p1: 0.000058
# Camera.p2: -0.000956
# Camera.k3: -0.021282

# Camera resolution
Camera.width: 640
Camera.height: 480
# Camera.width: 1280
# Camera.height: 800

# Camera frames per second
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#---------------------------------------------------------------------------------------
# IMU Parameters
#---------------------------------------------------------------------------------------

# Transformation from body-frame (imu) to left camera
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [ 0., 0., 1., 0.,
          -1., 0., 0., 0.,
           0.,-1., 0., 0.,
           0., 0., 0., 1.]
   # data: [1,0,0,0.1536,
   #       0,1,0,0.025,
   #       0,0,1,0.4004,
   #       0.0, 0.0, 0.0, 1.0]

# Do not insert KFs when recently lost
# InsertKFsWhenLost: 0

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 1.0e-3 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 1.0e-2 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 1.0e-6 # rad/s^1.5
IMU.AccWalk: 1.0e-4 # m/s^2.5
IMU.Frequency: 200

#---------------------------------------------------------------------------------------
# ORB Parameters
#---------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#---------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500
